!-- Conection to DB
spring.application.name=astroPI
spring.datasource.url=jdbc:postgresql://localhost:5432/astroPI_DB
spring.datasource.username=postgres
spring.datasource.password=astroAdminDB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
!Spring Security add Login - protect endpoints
spring.security.user.name=admin
spring.security.user.password=admin