package com.astropi.astropi.model;

import jakarta.persistence.*;
import lombok.Data;

import java.util.LinkedHashSet;
import java.util.Set;

@Entity
@Table(name = "roles")
@Data
public class Rol {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY) //ID AUTOGENERATED
private Long id;
private String nombre;

@ManyToMany
@JoinTable(
        name = "roles_permisos",
        joinColumns = @JoinColumn(name = "rol_id"),
        inverseJoinColumns = @JoinColumn(name = "permiso_id")
)
private Set<Permiso> permisos = new LinkedHashSet<>();
}
