package com.astropi.astropi.model;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "roles")
@Data
public class Rol {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY) //ID AUTOGENERATED
private Long id;
private String nombre;
}
